### ISSUE TITLE
Ability to access Async Singletons directly without await for its instance everytime.

### ISSUE THREAD

**Issue by dobresmith** [MelbourneDeveloper/ioc_container#10]
I think it defeats the purpose of naming it async singleton and having to await for the instance everytime to access it.
This features perfectly done in get_it
https://github.com/fluttercommunity/get_it/blob/master/lib/get_it.dart#L289

or i dont know if there is such feature, if there is please lmk.

**Comment by dobresmith** [comment]
Once the IocContainer is intialized
it should automatically add the instance to the scope 
eg ..addSingletonAsync<RxSharedPreferences>((container) async => (await SharedPreferences.getInstance()).rx)

once it returns the instance in the callback, it should be readly be accesible through just di<RxSharedPreferences>()

**Comment by MelbourneDeveloper** [comment]
Thanks @dobresmith . I will consider this. This seems to be the code where get_it waits for the future to finish, but I can't see clearly how it stores the completed `Future` value. Are you able to point me to some examples of how get_it uses this functionality?

I see some issues here, though... Firstly, it means creating an extra dictionary to hold the values as opposed to the `Future`s. That adds complexity and performance overhead. Secondly, it means that you still need to perform a check to make the value exists before you try to get it. If the `Future` did not complete, then you will either get an exception or a null; neither of these is very pretty. The nice thing about a `Future` (`await` keyword) is it gives you a neat syntax for getting the value safely and not needing to do the check in the first place. 

If the get_it implementation somehow avoids these issues, I can take a look at a similar approach for ioc_container.

```dart
   /// Async Singleton with dependencies
          final asyncResult = factoryFuncAsync!();

          isReadyFuture = asyncResult.then((instance) {
            serviceFactory.instance = instance;

            /// check if we are shadowing an existing Object
            final factoryThatWouldbeShadowed =
                _findFirstFactoryByNameAndTypeOrNull(instanceName,
                    type: T, lookInScopeBelow: true);

            final objectThatWouldbeShadowed =
                factoryThatWouldbeShadowed?.instance;
            if (objectThatWouldbeShadowed != null &&
                objectThatWouldbeShadowed is ShadowChangeHandlers) {
              objectThatWouldbeShadowed.onGetShadowed(instance);
            }

            if (!serviceFactory.shouldSignalReady && !serviceFactory.isReady) {
              serviceFactory._readyCompleter.complete(instance);
              serviceFactory.objectsWaiting.clear();
            }

            return instance;
```

**Comment by MelbourneDeveloper** [comment]
This is how I could see the awaited value API working. It has an advantage in the sense that you can use the second version in a non `async` context, but the issue is that if this version returns null, you will need to `await` the `Future` anyway, and this also demolishes null safety.

```dart
//Await keyword
final awaitedValue1 = await container.getAsync<String>();

//awaited value API (proposal)
final awaitedValue2 = container.hasAwaitedValue<String>() ? container.awaitedValue : null;
```

**Comment by MelbourneDeveloper** [comment]
@dobresmith any further thoughts on this? 

Any examples of get_it you can point me to?
