### ISSUE TITLE
Request for Feature: Dependency Retrieval by Name / String

### ISSUE THREAD

**Issue by Yetispapa** [MelbourneDeveloper/ioc_container#13]
Hi @MelbourneDeveloper,

First and foremost, I want to express my appreciation for your work on the ioc_container package for Flutter. I recently came across this package through a Reddit post and have been impressed with its capabilities.

I have a favor to ask. In a previous project, I migrated from the older "injector" package to your ioc_container package and had a smooth experience. However, as I started working on another project, I encountered an issue. In the "injector" package, I could register and retrieve dependencies by name or better say by a String, as shown in the examples below:

Registration:
`injector.registerDependency<Object>(builder, dependencyName: T.toString());`

Dependency Retrieval:
`Injector.appInstance.get<Object>(dependencyName: dependencyName);`

It seems that ioc_container currently lacks this particular feature. Would it be possible to include support for dependency retrieval by name in future releases of the package?

Thank you for your consideration, and regardless of the outcome, I want to express my gratitude for your contributions to the Flutter community.

**Comment by MelbourneDeveloper** [comment]
@Yetispapa, thanks for submitting the issue.

This is a common request. .NET added similar functionality in .NET 8. This gist is how you would achieve that with ioc_container

https://gist.github.com/MelbourneDeveloper/f9ec7ca5a9f0af099007b7c294402feb

Here is a more generic approach that works with many different types of services. There are a couple of footguns with this using this, though. I'm not sure I'd ever add these extensions, but you can easily add these extensions to give the container this behavior.

```dart
import 'package:ioc_container/ioc_container.dart';
import 'package:test/test.dart';

///Example service
class BigService {
  final String name;

  BigService(this.name);
  Future<void> callApi() => Future<void>.delayed(Duration(seconds: 1));

  ///We can check equality by the name(key)
  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is BigService && other.name == name;
  }

  @override
  int get hashCode => name.hashCode;
}

///These give us the functionality to add or
///access a service by key
extension KeyedExtensions on IocContainer {
  T? keyedService<T>(String key) => get<Map<String, T>>()[key];
  void setServiceByKey<T>(String key, T service) =>
      get<Map<String, T>>()[key] = service;
}

void main() {
  test('Keyed Services', () {
    var count = 0;

    final builder = (IocContainerBuilder()
      ..add((container) {
        //Increments the name (key) of the service so they are unique
        //Uuid would be better
        count++;
        var bigService = BigService(count.toString());
        bigService;
        container.setServiceByKey(count.toString(), bigService);
        return bigService;
      })
      ..addSingleton(
        (container) => <String, BigService>{},
      ));

    final container = builder.toContainer();

    final bigContainerOne = container<BigService>();
    final bigContainerTwo = container<BigService>();
    final bigContainerThree = container<BigService>();

    //Verifies the three names
    expect(bigContainerOne.name, '1');
    expect(bigContainerTwo.name, '2');
    expect(bigContainerThree.name, '3');

    //Verifies you can access these by key
    expect(container.keyedService<BigService>(bigContainerOne.name),
        bigContainerOne);

    expect(container.keyedService<BigService>(bigContainerTwo.name),
        bigContainerTwo);

    expect(container.keyedService<BigService>(bigContainerThree.name),
        bigContainerThree);
  });
}
```

**Comment by MelbourneDeveloper** [comment]
@Yetispapa , this is now part of the documentation [here](https://github.com/MelbourneDeveloper/ioc_container#keyed-services)

**Comment by Yetispapa** [comment]
Thanks @MelbourneDeveloper 👍
