### ISSUE TITLE
Default Behavior of getAsync

### ISSUE THREAD

**Issue by MelbourneDeveloper** [MelbourneDeveloper/ioc_container#6]
If you get a Future<> as a singleton, and that Future fails, the Future will always return an error for the container's lifespan. 

The solution is [here](https://github.com/MelbourneDeveloper/ioc_container/blob/47c3a3e6473e6634eca71312116271d295545f8d/lib/ioc_container.dart#L280)

It creates a scoped container and then only adds the singleton into the main container if the Future succeeds. It makes sense but can also mean that you end up running the same Future - or even other Futures more than once, needlessly. 

I'm wondering if this should be the default behavior or not... If it's the default, performance will likely suffer. If it's not the default, some singleton Futures will likely fail and wreck the container. Either way, you need to know the drawbacks of what is happening.

Not quite sure what they best choice is here.

**Comment by sunderee** [comment]
Performance > convenience. In my opinion, you shouldn't worry about user running multiple futures, or how they collect them. However, you can maintain two methods; safe one, and unsafe one.

On point about handling exceptions; I don't know about you, but async stuff I register in a container are third party dependencies (for example, `SharedPreferences.getInstance()`. If this thing fails, then maybe the developer has bigger fishes to fry first 😅

A bit of a tangent, but I would perhaps offer developers a way to pre-resolve their async dependencies. This could be an idea for a "safe" method as well.

**Comment by MelbourneDeveloper** [comment]
@sunderee thanks! I think this is in agreement with what I've been thinking

Check out this example. This is how you can safely resolve dependencies with `retry` as many times as necessary
https://github.com/MelbourneDeveloper/ioc_container/blob/f92bb3bd03fb3e3139211d0a8ec2474a737d7463/example/lib/main.dart#L77

**Comment by MelbourneDeveloper** [comment]
@sunderee done.

`getAsync()` is default, and `getAsyncSafe()` is there when you need it

Released:
https://pub.dev/packages/ioc_container
